name: DAG workflow 

on:
  workflow_dispatch:
    

jobs:
  
  job-1:
    runs-on: ubuntu-24.04
    steps:
      - run : echo"this is job1"

  job-2:
    runs-on: ubuntu-24.04
    steps:
     - run: echo"this is job2"

  job-3:
    runs-on: ubuntu-24.04
    needs:
      - job-1
      - job-2
    steps:
      - run: echo "this is job 3"
    
  jobs-4:
    runs-on: ubuntu-24.04
    needs:
     - job-2
     - job-3
  
    

  