name: secrect-vars

on: 
  workflow_dispatch:

jobs:
  staging-environment:
    runs-on: ubuntu-24.04
    environment: Staging
    env:
      EXAMPLE_REPOSITORY_SECRET:  ${{secrets.EXAMPLE_REPOSITORY_SECRET}} 
      EXAMPLE_REPOSITORY_VARIABLE: ${{vars.EXAMPLE_REPOSITORY_VARIABLE}}
      EXAMPLE_ENVIRONMENT_SECRET: ${{secrets.EXAMPLE_ENVIRONMENT_SECRET}}
      EXAMPLE_ENVIRONMENT_VARIABLE: ${{vars.EXAMPLE_ENVIRONMENT_VARIABLE}}
    steps :
     - name: Inspect values inside
       run: |
         echo "Repo secret (masked)": $EXAMPLE_REPOSITORY_SECRRET
         echo "Repo variable": $EXAMPLE_REPOSITORY_VARIABLE
         echo "Environment secret": $EXAMPLE_ENVIRONMENT_SECRET
         echo "Environment variable" $EXAMPLE_ENVIRONMENT_VARIABLE
  Production-environment:
    runs-on: ubuntu-24.04
    environment: Production
    env: 
      EXAMPLE_REPOSITORY_SECRET: ${{secrets.EXAMPLE_REPOSITORY_SECRET}}
      EXAMPLE_REPOSITORY_VARIABLE: ${{vars.EXAMPLE_REPOSITORY_VARIABLE}}
      EXAMPLE_ENVIRONMENT_SECRET: ${{secrets.EXAMPLE_ENVIRONMENT_VARIABLE}}
      EXAMPLE_ENVIRONMENT_VARIABLE: ${{vars.EXAMPLE_ENVIRONMENT_SECRET}}
    steps:
     - name: Inspect Production values
       run: |
         echo "Repo secret (masked)": $EXAMPLE_REPOSITORY_SECRET
         echo "Repo variable": $EXAMPLE_REPOSITORY_VARIABLEs
         echo "Environment secret" : $EXAMPLE_ENVIRONMENT_SECRET
         echo "Environment variable" : $EXAMPLE_ENVIRONMENT_VARIABLE
